version: '3.7'

services:
  django:
    build: ./
    container_name: userapi
    restart: always
    env_file:
      - user.env
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    restart: always
    container_name: database
    env_file:
      - user.env
    ports:
      - "5432:5432"
    volumes:
      - database-data:/var/lib/postgresql/data/


volumes:
  database-data: